### ISSUE TITLE
Suggestion: Add "Build In Jenkins" button in commit page.

### ISSUE THREAD

**Issue by lukaszjakubek** [ParameterizedBuilds/parameterized-builds#101]
Hello,

It might be nice feature to have "Build in Jenkins" button also on commit page.

**Comment by a-hacker** [comment]
Hi @lukaszjakubek,

I believe there already is one. 

![image](https://user-images.githubusercontent.com/3665996/31499311-692ab960-af32-11e7-9b70-fbdea8ac7bd1.png)

Were you thinking about a different page?

**Comment by lukaszjakubek** [comment]
Hi @a-hacker,

This one fire build on last commit in selected branch or tag. it's enought for 90% use cases, but sometimes I'd like to fire build on ona of past commites that is not tagged or branched, i.e HEAD^2 from list of commits or form commit detail page available on url: [domain]/projects/[project_name]/repos/[repo_name]/commits/[commit_hash]
![commit _ 975da5f71aa8 bitbucket](https://user-images.githubusercontent.com/7151151/31929907-f5e95a36-b89d-11e7-84a7-5db3e9158090.png)

**Comment by cstmgl** [comment]
I was looking exactly for the same thing. happy I passed by

**Comment by a-hacker** [comment]
I started looking into this about a month ago. Unfortunately, the commit page lacks certain bitbucket contexts elements that the other pages have. It's possible that we could get this added but it is unlikely that all of the special variables like `$BRANCH` will be available there.

**Comment by a-hacker** [comment]
Closing this as enhancements are no longer being worked on.
