### ISSUE TITLE
Configuring triggers using rest API

### ISSUE THREAD

**Issue by amirhadar** [ParameterizedBuilds/parameterized-builds#105]
We have lots of projects and repositories that we manage and provide CI services. Configuring the triggers in every project require lots of manual work.

If we add/remove parameter from the jenkins job we need to configure the triggers in all projects to adjust to the new parameters.

Ability to configure/update a trigger using REST API will allow us to automate the project creation and update.

**Comment by a-hacker** [comment]
That's an interesting idea. We already have some REST commands that are mostly used be the client-side code to fetch info from the server. I can definitely add some sort of GET and POST operations to handle job configs. I'll try to look into it but if you or anyone else wants to try to implement this feature, I'd recommend looking at com.kylenicholls.stash.parameterizedbuilds.rest.BuildResource

**Comment by patrickduboucher** [comment]
We would also be users for this idea. We are managing over 300 depots, and running jenkins triggers manually in each depot is the biggest blocker on on-boarding teams.

**Comment by andrew-demb** [comment]
@amirhadar @patrickduboucher 

Hello. I tried to solve this issue today, and during investigation how this plugin works and what capabilities provide Bitbucket I found, that problem can be solved via Bitbucket REST API.

I used these GET/PUT methods https://docs.atlassian.com/bitbucket-server/rest/6.7.1/bitbucket-rest.html#idp344 .

**Comment by a-hacker** [comment]
Hey @andrew-demb. While that is a workaround for now I do not recommend it unless necessary. It requires an understanding of how the plugin stores data and if done incorrectly, can cause the plugin to break. This is also not something that is considered user facing so it is possible that future versions could break any automation using those rest methods.

I think it would still be valuable to have more intuitive rest endpoints for this plugin. Those endpoints would ensure that data does not become corrupt from user error and would be more consistent with how the settings page works.

If you are still interested in working on this issue, I'd recommend starting by updating the [swagger spec](https://github.com/KyleLNicholls/parameterized-builds/blob/master/docs/spec.yml). That way I can review it and make sure that your implementation is consistent with the other rest endpoints I have already implemented.

**Comment by MohgaNabil** [comment]
I'd also totally advocate for this idea 🥇 We've more than 100 repos for which we need to configure the plugin for which is quite a tedious manual task. Therefore, we currently use a script to create those configs. So this would be absolutely handy (As despite our scripts manages to create those configs, they don't display in the UI 🤷‍♀️ ). I'd be willing to help and bring this up to speed 🙋‍♀️  .

**Comment by a-hacker** [comment]
Closing this as enhancements are no longer being worked on.
