### ISSUE TITLE
Support Multibranch Pipeline Pull Requests as sub jobs

### ISSUE THREAD

**Issue by bhoppeadoy** [ParameterizedBuilds/parameterized-builds#109]
@a-hacker, thanks for the clarification so I'm starting this new issue.

Here's the setup:
BitBucket Server v5.4.1
Parameterized-builds v3.2.0
Jenkins v2.94
BitBucket Branch Source Plugin v2.2.7

I'm using BitBucket Branch Source as the branch source for my multibranch pipeline (instead of Git). This source creates Pull Requests as subjobs instead of a regular branch. Branch jobs are seen as:

/job/my-project/job/develop/
/job/my-project/job/feature%2Fsome-feature-title/

The job path for the pull request shows as:
/job/my-project/view/change-requests/job/PR-13/

Where '13' is the BitBucket pull request id, such as:
https://bitbucket/projects/my-project/repos/my-repo/pull-requests/13/overview

I see that from #93, you have a PR trigger a build. This won't work because the PR build doesn't exist yet when the PR is first opened. A scan has to happen for the multibranch pipeline to see the pull request and create the build for it. A PR_OPENED and PR_DELETED are pretty much the same thing as REF_CREATED and REF_DELETED.

I'm thinking all PR triggers should invoke scan. Only thing that should invoke a specific build directly is PUSH_EVENT and MANUAL. The MANUAL trigger in the Pull Request view would call the PR subjob path instead of the branch subjob path.

Brandon

**Comment by bhoppeadoy** [comment]
Hi, just checking if this is possible. 

My workaround currently is to use Parameterized-Builds plugin to trigger Jenkins for REF_CREATED, REF_DELETED and PUSH_EVENT only.

I then use Pull Request Notification plugin to handle the pull request side of things. It works, but I'd rather just use a single plugin to handle these and I prefer the your plugin for its simplicity and I like that MANUAL trigger better.

Thanks

**Comment by a-hacker** [comment]
I don't know too much about the Pull Request Notification plugin but if it's working for you, that sounds like a reasonable workaround.

I have a few other feature requests I want to investigate before this one so I wouldn't expect an update soon. Of course, anyone else is welcome to look into implementing this feature and I'd be more than happy to help them do so.

**Comment by michallaskowski** [comment]
@a-hacker Hi. I started working on this and opened a PR. This is a blocker for me adopting multibranch pipelines in my company.

@bhoppeadoy could you assist with testing my changes, to be sure Jenkins is triggered correctly?

**Comment by a-hacker** [comment]
Closing this as enhancements are no longer being worked on.
