### ISSUE TITLE
Add option to suppress triggering a Jenkins notification when repo update is automated

### ISSUE THREAD

**Issue by James-Newman** [ParameterizedBuilds/parameterized-builds#134]
If, as part of a jenkins job, the repository is updated by jenkins, then this will trigger another job. This has the potential to get stuck into an infinite loop of triggering, running, updating, triggering etc.

A use case for such automatic updating might be updating version numbers automatically for each build.

Similar plugins will suppress triggers when the committer name or message match a pattern or regex.

**Comment by a-hacker** [comment]
Hi @James-Newman. Adding a user whitelist and/or blacklist feature sounds like a good idea. We do currently have the ability to filter based on what files or directories are changed, filter which branches are changed, and what events trigger a build. I think those are sufficient enough to make this a low priority item. However, if you would like work on this I just started a Gitter chat here: https://gitter.im/parameterized-builds/Lobby where we can discuss what needs to be done.

@greenstevester, if you are still interested in contributing, this may be a good issue to get started on. At the very least, you should join the Gitter linked above and we can figure something out!

**Comment by a-hacker** [comment]
Filters to prevent builds based on user or commit message added in 4.0.10. Thanks @rgaduput!
