### ISSUE TITLE
Working with Folders plugin

### ISSUE THREAD

**Issue by grimmtooth** [ParameterizedBuilds/parameterized-builds#135]
We're migrating to a new server - from Jenkins 1 to Jenkins 2. In the process we've also added the Folders plugin because managing over 2000 jobs at the top level was a real drag.

As we migrate Bitbucket projects over, we're finding that jobs that are in folders are not being triggered unless we incorporate the entire project path.  For example, previously we could specify 

`SampleJob`

and the job would be triggered, no problem.

But once we embedded it in a hierarchy like

`Division/Department/Project/SampleJob`

The plugin reports that it can't find the job.  To get the job to trigger, I had to use the tail-end of the actual URL:

`Division/job/Department/job/Project/job/SampleJob`

The plugin of course prepends `hostName:port/job/` to the name of the job before POSTing to the host.

So, is there a way to make this plugin deal with a folder hierarchy? If not, you might want to add this scenario to your documentation.

Cheers for the great plugin!

**Comment by a-hacker** [comment]
Hi @grimmtooth, you are not the first to run into this scenario. Considering the relatively simple yet somewhat tedious work-around you mentioned, I don't believe adding specific folder support it a high priority item. However, I will update our documentation!

**Comment by a-hacker** [comment]
Closing this as enhancements are no longer being worked on.
