### ISSUE TITLE
All reviewer approved Pull Request ,then trigger Jenkins

### ISSUE THREAD

**Issue by VivianZhang1990** [ParameterizedBuilds/parameterized-builds#139]
I noticed it can trigger Jenkins when someone pressed "approve" button after create a pull request.

But i hope that the action happened only if all the reviewer approved . Is there any method to fix it?

**Comment by a-hacker** [comment]
Hi @VivianZhang1990. That's for submitting this issue.

The PR Approved trigger is designed to trigger every time a PR is approved rather than when all reviewers approve. Therefore, there is really nothing to fix.

However, we could probably look into adding a built-in variable along the lines of $BRANCH or $PRURL that would give you the information you need. Would this be a suitable compromise?

**Comment by VivianZhang1990** [comment]
thanks for your answer.
But  what's the variable used for and how to use the it?

**Comment by a-hacker** [comment]
That's an excellent question. There's a lot of information about pull requests that we could expose. For instance we could have a $PRAPPROVALS which would be the number of approvals the PR has received and $PRREVIEWERCOUNT which would be the number of reviewers on the PR. If you then passed these values as parameters to your Jenkins job, you would know that your job should do it's task when the two values are equal.

Personally, I'm not sure what the desired use case is for triggering jobs on PR approvals but if that information is helpful to the community, then I think we can do that.

**Comment by Dushelov** [comment]
@a-hacker Any option to do it for cloud bitbucket? We need trigger after all approves and before merge. Maybe some other triggers can be used?

**Comment by RashmiNema** [comment]
Hi @Dushelov ,
I am looking for the same scenario. Once all reviewers approved the pull request, jenkins build should trigger. Have you got the solution?
Could you please help me.
Thanks,
Rashmi

**Comment by willehrlich** [comment]
The workaround I have been using for this has been to have a job in Jenkins that gets triggered on approve.  Inside that job, I make an api call back to Bitbucket to grab the details of the pull request and determine if everyone has approved.  If not everyone has approved, it triggers an email to the rest of the reviewers that someone else has approved and we are waiting on their code review to move forward.  If everyone has approved, I have it email me to let me know it is time to do the final review and merge.

**Comment by a-hacker** [comment]
Closing this as enhancements are no longer being worked on.
