### ISSUE TITLE
Allow multiple jenkins servers per project/globally

### ISSUE THREAD

**Issue by a-hacker** [ParameterizedBuilds/parameterized-builds#178]
Users should be able to specify multiple jenkins servers per project. The Jenkins settings should be updated to allow an arbitrary number of jenkins servers. Once #177 is done, this will be as simple as adding a "Create New Server" button on those pages.

We do need to be careful about deleting servers that have jobs using that server though. We could traverse through each repository and look for orphaned jobs and raise an error if there are any. However, on the global level this will likely be slow on servers with many projects and repositories. Another option would be to warn users that any jobs using that server will not trigger if a server without that nickname is not defined. This would be quick and easier but may result in a worse user experience.

**Comment by mjdean1994** [comment]
This feature would be **huge** for my team. Would really love to see this work get prioritized.

**Comment by a-hacker** [comment]
Hey @mjdean1994. Glad to here it! I think this is a useful feature for many users which is why its one of my top items. However, it's been a significant undertaking because the plugin was just not designed with this feature in mind.

Most of the work I've been doing here lately has been working up to this. If you'd like to track the current status and what still needs doing, I've created a project for this task [here](https://github.com/KyleLNicholls/parameterized-builds/projects/2).

**Comment by yorammi** [comment]
I vote for this feature as well. I need it for transferring jobs from one Jenkins server to a new one, and doing it in phases

**Comment by AdamKanawat** [comment]
This will be helpful since we can switch between staging and production per repo. I VOTE!

**Comment by a-hacker** [comment]
Closing this as enhancements are no longer being worked on.
