### ISSUE TITLE
Filter for mergeability status

### ISSUE THREAD

**Issue by SofteqDG** [ParameterizedBuilds/parameterized-builds#190]
In the latest version of plugin jenkins job will be triggered if pull request has merge conflicts with target branch. Bitbucket can report if pull request can be or can not be merged into target branch ([link to documentation](https://docs.atlassian.com/bitbucket-server/javadoc/5.1.5/api/reference/com/atlassian/bitbucket/pull/PullRequestService.html#canMerge(int,%20long))). 

It would be awesome to add new filter called **PR Merge Conflicts Filter** with two selectable options:
**PR HAS CONFLICTS** - trigger job if pull request has conflicts
**PR HAS NO CONFLICTS** - trigger job if pull request has no conflicts

User should be able to use any combination of these options but they should be deselected by default in order to trigger job for any state of pull request.

**Comment by a-hacker** [comment]
Hi @SofteqDG. I think that is a great idea! Would you feel comfortable working on this feature yourself?

**Comment by a-hacker** [comment]
Closing this as enhancements are no longer being worked on.
