### ISSUE TITLE
Main configuration can use "$PRDESTINATION" in job name, but makes "Build in Jenkins" not work

### ISSUE THREAD

**Issue by davidmichaelkarr** [ParameterizedBuilds/parameterized-builds#192]
We've started using PBJ in BitBucket v5.10.1.  It basically works.  We decided to customize the job name, adding "$PRDESTINATION" to the job name, so pull request builds go into a subjob based on the target branch.

This works fine on new pull requests and when commits are pushed to the pull request branch.

However, we later discovered that this breaks "Build in Jenkins".  It just says "Job not found".

**Comment by a-hacker** [comment]
Hey @davidmichaelkarr, this is because the PR-related variables are currently only available in PR-specific triggers. It looks like we could probably look up if a PR exists for a given branch though. Would you be interested in working on implementing this update? I'd be happy to provide assistance.

**Comment by davidmichaelkarr** [comment]
The "Build in Jenkins" operation is done from the view of a pull request, which I assume would have a destination.

I've never worked on a BitBucket plugin before. I don't have admin rights in our BitBucket installation, so I don't know how I would test it.

**Comment by a-hacker** [comment]
Looking at the code, I think we are passing the prId to the rest endpoint for triggering a job but we don't actually use it. It should be pretty simple to resolve the PR-specific variables. The [BuildResource](https://github.com/KyleLNicholls/parameterized-builds/blob/aa7ac845a8859e7d28a504c2101ddddec4f06b6a/src/main/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResource.java#L71) class has access to a [PullRequestService](https://docs.atlassian.com/bitbucket-server/javadoc/5.1.5/api/reference/com/atlassian/bitbucket/pull/PullRequestService.html) object to look up the PR. Then it's just a matter of adding the bitbucket variables in the triggerBuild method.

Luckily you don't have to have a real bitbucket server to test the code. I wrote up a [guide](https://github.com/KyleLNicholls/parameterized-builds/wiki/Developer-Guide) to set up a developer environment awhile back.

**Comment by a-hacker** [comment]
Closing this as enhancements are no longer being worked on.
