### ISSUE TITLE
enable dependabot & security monitoring

### ISSUE THREAD

**Issue by rursprung** [ParameterizedBuilds/parameterized-builds#198]
i have no personal experience with this, but based on the docu it seems a good idea:

* set up the automated security monitoring: https://help.github.com/en/articles/configuring-automated-security-fixes
* enable dependabot which automatically offers dependency updates whenever it finds that some are available: https://github.com/marketplace/dependabot-preview

**Comment by a-hacker** [comment]
That seems helpful. Unfortunately, I don't have permissions to integrate new apps or add security configurations. @KyleLNicholls, could you assist with this ?

**Comment by a-hacker** [comment]
Dependabot and security alerts added.
