### ISSUE TITLE
improve code quality: add static code analysis

### ISSUE THREAD

**Issue by rursprung** [ParameterizedBuilds/parameterized-builds#199]
i would suggest to enable [PMD](https://pmd.github.io/) for the build to catch problems in the code early on. there's a [maven plugin](https://pmd.github.io/pmd-6.15.0/pmd_userdocs_tools_maven.html) for it which can be integrated into the build process. a plugin exists for eclipse and i've seen that there's also one for IntelliJ (but i haven't used that one and the reviews seem to be mixed).

this is similar to #197, but with a focus on the actual code rather than just the formatting of it. the steps for enabling it should be similar to those for enabling checkstyle.

**Comment by rursprung** [comment]
a pure github alternative to having PMD integrated into the maven build could be to use https://github.com/marketplace/lgtm (just found it - haven't used it, can't comment on it any further)

however, for this to work i think all commits would have to go through pull requests to be checked. and the feedback would only be available once the PR has been opened - with PMD integrated into the build, it can be verified locally.
or maybe both can be used in tandem and add value to each other? just guessing here...

**Comment by a-hacker** [comment]
I think this is a great idea! I looked into PMD in the past but hadn't gotten around to actually adding automated code checking yet.

As for lgtm, that looks interesting but I'd rather just start with one new tool for now and go from there. 

Would you be willing to take on this task?

**Comment by rursprung** [comment]
sorry, i don't have the time to work on this for now.

**Comment by a-hacker** [comment]
Closing this as enhancements are no longer being worked on.
