### ISSUE TITLE
Add email address of all PR reviews - build parameter

### ISSUE THREAD

**Issue by twistedvip** [ParameterizedBuilds/parameterized-builds#228]
Hello,

I have found this plugin very useful and have slowly begun having our team switch to using this for all our PR in order to run unit tests, static analysis, etc. Our jenkins job is set up to send out an email at the end of the test with a report of the results.

While I can (and do) link the results file link to the Bitbucket Build Status, unfortunately a lot of team members are seemingly too lazy to look at the BB build status and prefer to see an email instead, but I would only want the email sent to those the results would apply to (i.e. the PR reviewers).

Therefore, I have an enhancement/feature request. I saw that the $PREMAIL was recently added as a feature which is definitely a nice step in the right direction which our team wants. However, I'm requesting a step further and add a new variable such as '$PRREVIEWEREMAIL' which will provide the list of ALL PR reviewers' email.

The plugin "https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket" currently provides this as a variable `${PULL_REQUEST_REVIEWERS_EMAIL}`, but I prefer this plugin A LOT more as its much more friendly for using Jenkins Build Parameters.

Please let me know if this is something you would consider a possible feature that could be added, as it would greatly help our team's Continuous Integration process!

**Comment by a-hacker** [comment]
Hi @twistedvip. I've gotten several requests around PR reviewers/approvals. My impression is that a fair share of users would like to see better support for their approval workflow but those workflows often differ, sometimes significantly. I would like to add a feature like this but I want to make sure it can meet the demands of as many users as possible. I'm not sure that adding more variables will be flexible enough for different use cases.

For now, you might want to look into the Bitbucket rest api. There's an [endpoint](https://docs.atlassian.com/bitbucket-server/rest/6.7.1/bitbucket-rest.html#idp275) that should give you info on all reviewers, including email addresses.

**Comment by twistedvip** [comment]
Good point, I definitely know that the plugin I referenced above has 1001 different variables and I think it makes it more overwhelming.
Our team is always up for possibly having a different approval workflow, if it is shown to be more effective/efficient. I'll keep checking back here in case a solution for this might be checked in. For the meantime, I'll check out the rest api and see what I can dig up. Thanks!

**Comment by a-hacker** [comment]
Closing this as enhancements are no longer being worked on.
