### ISSUE TITLE
after update Bitbucket  to version 6.10.0 I can't set Jenkins Settings

### ISSUE THREAD

**Issue by aaf1** [ParameterizedBuilds/parameterized-builds#263]
Parameterized Builds for Jenkins plugin version 4.0.11
Bitbucket version BitBucket Server v6.10.0
Jenkins Version v2.190.2

after update Bitbucket  to version 6.10.0 I can't set Jenkins Settings

![image](https://user-images.githubusercontent.com/49514160/73647291-3a8e6e00-468c-11ea-8f3c-a90bc7064a97.png)

In hook configs i can choose global jenkins server, it was configured  in old bitbucket version, and it works. 
I think problem only at settings page.

**Comment by a-hacker** [comment]
Hi @aaf1. Thank you for the bug report. If you open your browser console, do you see any error messages reported there? Also, if you have access to your Bitbucket logs, could you check if there are any log messages to seem to be related when you try to access this page?

**Comment by aaf1** [comment]
in projects settings are available
![image](https://user-images.githubusercontent.com/49514160/73739589-91ad4500-4757-11ea-80b4-17618dea543c.png)


global properties are not 
Request URL: https://stash.vsegda.da/plugins/servlet/jenkins

<!DOCTYPE html><html lang="ru"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>Jenkins Settings - Bitbucket</title><script>
window.WRM=window.WRM||{};window.WRM._unparsedData=window.WRM._unparsedData||{};window.WRM._unparsedErrors=window.WRM._unparsedErrors||{};
WRM._unparsedData["com.atlassian.plugins.atlassian-plugins-webresource-plugin:context-path.context-path"]="\u0022\u0022";
WRM._unparsedData["com.atlassian.bitbucket.server.bitbucket-webpack-INTERNAL:date-format-preference.data"]="\u0022\u0022";
WRM._unparsedData["com.atlassian.analytics.analytics-client:policy-update-init.policy-update-data-provider"]="false";
WRM._unparsedData["com.atlassian.analytics.analytics-client:programmatic-analytics-init.programmatic-analytics-data-provider"]="false";
WRM._unparsedData["com.atlassian.plugins.base-hipchat-integration-plugin:configure-integration-data.configure-integration"]="{\u0022inviteEnabled\u0022:true}";
if(window.WRM._dataArrived)window.WRM._dataArrived();</script>
<link type="text/css" rel="stylesheet" href="/s/cf9152bdf58562b190dc53df9f26a456-CDN/-428881039/c4995b3/59/7778f81f0137835d6a29c77fe8708f98/_/download/contextbatch/css/_super/batch.css" data-wrm-key="_super" data-wrm-batch-type="context" media="all">
<link type="text/css" rel="stylesheet" href="/s/c1e0e6ff7e658c517cbfdee80cef168d-CDN/-428881039/c4995b3/59/5b67c300cc3e32384e117a8ae404441a/_/download/contextbatch/css/bitbucket.layout.admin,bitbucket.layout.entity,bitbucket.layout.base,atl.admin,-_super/batch.css" data-wrm-key="bitbucket.layout.admin,bitbucket.layout.entity,bitbucket.layout.base,atl.admin,-_super" data-wrm-batch-type="context" media="all">
<script type="text/javascript" src="/s/d449e778a5b5dce261ad9a68ae894c53-CDN/-428881039/c4995b3/59/7778f81f0137835d6a29c77fe8708f98/_/download/contextbatch/js/_super/batch.js?locale=en-US" data-wrm-key="_super" data-wrm-batch-type="context" data-initially-rendered></script>
<script type="text/javascript" src="/s/204b65106930738bac3503d05596991a-CDN/-428881039/c4995b3/59/5b67c300cc3e32384e117a8ae404441a/_/download/contextbatch/js/bitbucket.layout.admin,bitbucket.layout.entity,bitbucket.layout.base,atl.admin,-_super/batch.js?locale=en-US" data-wrm-key="bitbucket.layout.admin,bitbucket.layout.entity,bitbucket.layout.base,atl.admin,-_super" data-wrm-batch-type="context" data-initially-rendered></script>
<script type="text/javascript" src="/download/contextbatch/js/bitbucket.layout.admin,bitbucket.layout.entity,bitbucket.layout.base,atl.admin,-_super/batch.js?cache=false&amp;locale=en-US" data-wrm-key="bitbucket.layout.admin,bitbucket.layout.entity,bitbucket.layout.base,atl.admin,-_super" data-wrm-batch-type="context" data-initially-rendered></script>
<script type="text/javascript" src="/s/d41d8cd98f00b204e9800998ecf8427e-CDN/-428881039/c4995b3/59/4.0.11/_/download/batch/com.kylenicholls.stash.parameterized-builds:jenkins-settings-form/com.kylenicholls.stash.parameterized-builds:jenkins-settings-form.js" data-wrm-key="com.kylenicholls.stash.parameterized-builds:jenkins-settings-form" data-wrm-batch-type="resource" data-initially-rendered></script>
<meta name="application-name" content="Bitbucket"><link rel="shortcut icon" type="image/x-icon" href="/s/-428881039/c4995b3/59/1.0/_/download/resources/com.atlassian.bitbucket.server.bitbucket-webpack-INTERNAL:favicon/favicon.ico" /><meta name="decorator" content="atl.admin"><meta name="activeTab" content="jenkins-admin-tab"><link rel="search" href="https://stash.vsegda.da/plugins/servlet/opensearch-descriptor" type="application/opensearchdescription+xml" title="Bitbucket code search"/></head><body class=" bitbucket-theme admin"><ul id="assistive-skip-links" class="assistive"><li><a href="#content">Skip to content</a></li></ul><div id="page"><header id="header" role="banner"><section class="notifications"><script type="text/javascript">require('bitbucket/internal/feature/integrity/alert').init([]);</script></section><nav class="aui-header aui-dropdown2-trigger-group" role="navigation"><div class="aui-header-inner"><div class="aui-header-before"><a class=" aui-dropdown2-trigger app-switcher-trigger" aria-controls="app-switcher" aria-haspopup="true" role="button" tabindex="0" data-aui-trigger href="#app-switcher"><span class="aui-icon aui-icon-small aui-iconfont-appswitcher">Linked Applications</span></a><div id="app-switcher" class="aui-dropdown2 aui-style-default" role="menu" aria-hidden="true" data-is-switcher="true" data-environment="{&quot;isUserAdmin&quot;:true,&quot;isAppSuggestionAvailable&quot;:false,&quot;isSiteAdminUser&quot;:true}"><div role="application"><div class="app-switcher-loading">Loading&hellip;</div></div></div></div><div class="aui-header-primary"><h1 id="logo" class="bitbucket-header-logo"><a href="https://stash.vsegda.da">Bitbucket</a></h1><ul class="aui-nav"><li class=" projects-link"><a href="/projects" class="projects-link" data-web-item-key="com.atlassian.bitbucket.server.bitbucket-server-web-fragments:projects-menu">Projects</a></li><li class=" recent-repositories"><a id="repositories-menu-trigger"  class=" aui-dropdown2-trigger" aria-controls="com.atlassian.bitbucket.server.bitbucket-server-web-fragments-repositories-menu" aria-haspopup="true" role="button" tabindex="0" data-aui-trigger>Repositories</a><div id="com.atlassian.bitbucket.server.bitbucket-server-web-fragments-repositories-menu" class="aui-dropdown2 aui-style-default" role="menu" aria-hidden="true"><div role="application"><div class="aui-dropdown2-section recent-repositories-section"><strong role="presentation" class="aui-dropdown2-heading">Recently viewed</strong><ul class="aui-list-truncate" role="presentation"></ul></div><div class="aui-dropdown2-section public-repo-list-link-section"><ul class="aui-list-truncate" role="presentation"><li role="presentation"><a href="/repos?visibility=public" class="public-repos-link icon-repository" title="View all publicly accessible repositories in Bitbucket" data-web-item-key="com.atlassian.bitbucket.server.bitbucket-server-web-fragments:public-repo-list-link">View all public repositories</a></li></ul></div></div></div></li><li class=""><a id="people-menu-trigger"  class=" aui-dropdown2-trigger" aria-controls="com.stiltsoft.stash.graphs-people-menu" aria-haspopup="true" role="button" tabindex="0" data-aui-trigger>People</a><div id="com.stiltsoft.stash.graphs-people-menu" class="aui-dropdown2 aui-style-default" role="menu" aria-hidden="true"><div role="application"><div class="aui-dropdown2-section people-section"><strong role="presentation" class="aui-dropdown2-heading">Recently viewed</strong><ul class="aui-list-truncate" role="presentation"></ul></div><div class="aui-dropdown2-section people-link-section"><ul class="aui-list-truncate" role="presentation"><li role="presentation"><a href="/plugins/servlet/people" data-web-item-key="com.stiltsoft.stash.graphs:people-link">All users</a></li></ul></div></div></div></li></ul></div><div class="aui-header-secondary"><ul class="aui-nav"><li><div id="quick-search-loader"></div><script>jQuery(document).ready(function () {require(['bitbucket-plugin-search/internal/component/quick-search/quick-search-loader'], function (loader) {loader.onReady('#quick-search-loader');}) ;}) ;</script></li><li class=" help-link"title="Help"><a class=" aui-dropdown2-trigger aui-dropdown2-trigger-arrowless" aria-controls="com.atlassian.bitbucket.server.bitbucket-server-web-fragments-help-menu" aria-haspopup="true" role="button" tabindex="0" data-aui-trigger><span class="aui-icon aui-icon-small aui-icon-small aui-iconfont-question-circle">Help</span></a><div id="com.atlassian.bitbucket.server.bitbucket-server-web-fragments-help-menu" class="aui-dropdown2 aui-style-default" role="menu" aria-hidden="true"><div role="application"><div class="aui-dropdown2-section help-items-section"><ul class="aui-list-truncate" role="presentation"><li role="presentation"><a href="http://docs.atlassian.com/bitbucketserver/docs-0610/Bitbucket+Server+documentation?utm_campaign=in-app-help&amp;amp;utm_medium=in-app-help&amp;amp;utm_source=stash" title="Go to the online documentation for Bitbucket" data-web-item-key="com.atlassian.bitbucket.server.bitbucket-server-web-fragments:general-help">Online help</a></li><li role="presentation"><a href="https://www.atlassian.com/git?utm_campaign=learn-git&amp;utm_medium=in-app-help&amp;utm_source=stash" title="Learn about Git commands &amp; workflows" data-web-item-key="com.atlassian.bitbucket.server.bitbucket-server-web-fragments:learn-git">Learn Git</a></li><li role="presentation"><a href="/getting-started" class="getting-started-page-link" title="Overview of Bitbucket features" data-web-item-key="com.atlassian.bitbucket.server.bitbucket-server-web-fragments:getting-started-page-help-link">Welcome to Bitbucket</a></li><li role="presentation"><a href="/#" class="keyboard-shortcut-link" title="Discover keyboard shortcuts in Bitbucket" data-web-item-key="com.atlassian.bitbucket.server.bitbucket-server-web-fragments:keyboard-shortcuts-help-link">Keyboard shortcuts</a></li></ul></div></div></div></li><li class="selected admin-link"title="Administration"><a href="/admin" class="admin-link" title="Administration" data-web-item-key="com.atlassian.bitbucket.server.bitbucket-server-web-fragments:administration-menu"><span class="aui-icon aui-icon-small aui-iconfont-settings">Administration</span></a></li><li class=" alerts-menu"title="View system alerts"><a href="#alerts" id="alerts-trigger" class="alerts-menu" title="View system alerts" data-web-item-key="com.atlassian.bitbucket.server.bitbucket-server-web-fragments:global-alerts-menu-item">Alerts</a></li><li class="inbox-menu" title="View your unapproved pull requests"><a href="#inbox" id="inbox-trigger" data-aui-trigger aria-controls="inline-dialog-inbox-pull-requests-content" aria-label="View your unapproved pull requests" ><span class="aui-icon aui-icon-small aui-iconfont-tray">Inbox</span></a><aui-inline-dialog id="inline-dialog-inbox-pull-requests-content" alignment="bottom right"><aui-spinner size="medium" /></aui-inline-dialog></li><li class="user-dropdown"><a class=" aui-dropdown2-trigger user-dropdown-trigger aui-dropdown2-trigger-arrowless" aria-controls="user-dropdown-menu" aria-haspopup="true" role="button" title="Logged in as Александр Фетисов (aanfetisov)" data-container=".aui-header-secondary" tabindex="0" data-aui-trigger><span id="current-user" class="aui-avatar aui-avatar-small" data-emailaddress="Aleksandr.A.Fetisov@homecredit.ru" data-username="aanfetisov" data-avatarurl-small="/users/aanfetisov/avatar.png?s=48&amp;v=1558539313000"><span class="aui-avatar-inner"><img src="/users/aanfetisov/avatar.png?s=48&amp;v=1558539313000" alt="Logged in as Александр Фетисов (aanfetisov)" /></span></span></a><div id="user-dropdown-menu" class="aui-dropdown2 aui-style-default" role="menu" aria-hidden="true"><div role="application"><div class="aui-dropdown2-section user-settings-section"><ul class="aui-list-truncate" role="presentation"><li role="presentation"><a href="/profile" data-web-item-key="com.atlassian.bitbucket.server.bitbucket-server-web-fragments:profile-menu-item">View profile</a></li><li role="presentation"><a href="/account" data-web-item-key="com.atlassian.bitbucket.server.bitbucket-server-web-fragments:account-menu-item">Manage account</a></li><li role="presentation"><a href="/plugins/servlet/upm/requests?source=header_user" id="upm-requests-link" data-web-item-key="com.atlassian.upm.atlassian-universal-plugin-manager-plugin:bitbucket-upm-requests-menu">Atlassian Marketplace</a></li></ul></div><div class="aui-dropdown2-section user-activities-graph-section"><ul class="aui-list-truncate" role="presentation"><li role="presentation"><a href="/plugins/servlet/user-contributions/aanfetisov" data-web-item-key="com.stiltsoft.stash.graphs:user-activities-graph-profile-item">My activity</a></li></ul></div><div class="aui-dropdown2-section user-logout-section"><ul class="aui-list-truncate" role="presentation"><li role="presentation"><a href="/j_atl_security_logout" class="logout-link" data-web-item-key="com.atlassian.bitbucket.server.bitbucket-server-web-fragments:logout-menu-item">Log out</a></li></ul></div></div></div></li></ul></div></div> </nav> </header><section id="content" role="main" tabindex="-1" data-timezone="-180" ><header class="aui-page-header"><section class="notifications"></section><div class="aui-page-header-inner"><div class="aui-page-header-main entity-item"><h1><span class="entity-name">Administration</span></h1></div><div class="aui-page-header-actions"><div id='upm-notifications-container'></div></div></div></header><div class="aui-page-panel content-body" id="aui-page-panel-content-body" tabindex="-1"><div class="aui-page-panel-inner"><div class="aui-page-panel-nav"><nav class="aui-navgroup aui-navgroup-vertical" role="navigation"><div class="aui-navgroup-inner"><ul class="aui-nav"><li><a href="/admin"" >Overview</a></li></ul><div class="aui-nav-heading"><strong>Accounts</strong></div><ul class="aui-nav"><li><a href="/admin/users" class="icon-admin-users" title="Edit individual user details, passwords and groups membership."" >Users</a></li><li><a href="/admin/groups" class="icon-admin-groups" title="Create groups and manage the users within each group."" >Groups</a></li><li><a href="/plugins/servlet/teams" class="icon-admin-groups" title="Organize users and groups into teams."" >Teams</a></li><li><a href="/admin/permissions" class="icon-admin-permissions" title="Configure global user permissions."" >Global permissions</a></li><li><a href="/admin/authentication" class="icon-admin-authentication" title="Configure access, privacy and spam prevention settings."" >Authentication</a></li><li><a href="/plugins/servlet/authentication-config" title="Configure single sign-on."" >SSO 2.0</a></li><li><a href="/admin/avatars" class="icon-admin-avatars" title="Configure user avatar settings."" >Avatars</a></li><li><a href="/plugins/servlet/embedded-crowd/directories/list"id="user_directories" class="icon-admin-userdirectory" title="Connect Bitbucket to user directory servers - Active Directory, Crowd, LDAP and JIRA"" >User Directories</a></li></ul><div class="aui-nav-heading"><strong>Settings</strong></div><ul class="aui-nav"><li><a href="/admin/server-settings" class="icon-admin-serversettings" title="Configure HTTP, SSH and other server settings."" >Server settings</a></li><li><a href="/admin/db" class="icon-admin-database" title="View and migrate database configurations."" >Database</a></li><li><a href="/admin/storage"" >Storage</a></li><li><a href="/plugins/servlet/customize-application-navigator"id="custom-apps-admin-link" title="Add links to the Application Navigator"" >Application Navigator</a></li><li><a href="/plugins/servlet/applinks/listApplicationLinks"id="configure-application-links" title="Configure links to other applications, including Atlassian products."" >Application Links</a></li><li><a href="/admin/mail-server" class="icon-admin-mailserver" title="Configure the SMTP server used to send notification emails."" >Mail server</a></li><li><a href="/admin/license" class="icon-admin-licensing" title="View and configure license information."" >Licensing</a></li><li><a href="/admin/clustering" class="icon-admin-clustering" title="View clustering information."" >Clustering</a></li><li><a href="/plugins/servlet/admin/mirrors" class="icon-admin-mirroring" title="View servers mirroring projects and repositories"" >Mirrors</a></li><li><a href="https://stash.vsegda.da/admin/announcement-banner" title="Create a system-wide banner to communicate important information."" >Announcement banner</a></li><li><a href="/plugins/servlet/analytics/configuration"id="analytics-configuration" title="Configure analytics data collection settings."" >Analytics</a></li></ul><div class="aui-nav-heading"><strong>Add-ons</strong></div><ul class="aui-nav"><li><a href="/plugins/servlet/upm/marketplace?source=side_nav_find_new_addons"id="upm-marketplace-link" title="Find and install apps from the Atlassian Marketplace."" >Find new apps</a></li><li><a href="/plugins/servlet/upm?source=side_nav_manage_addons"id="upm-admin-link" title="Install, update, enable, and disable apps."" >Manage apps</a></li><li class="aui-nav-selected"><a href="/plugins/servlet/jenkins"id="reminder-config-link"" >Jenkins Settings</a></li><li><a href="/plugins/servlet/hipchat/configure"id="bitbucket-hipchat-admin-label" title="Receive Bitbucket notifications in Hipchat"" >Hipchat integration</a></li></ul><div class="aui-nav-heading"><strong>Support</strong></div><ul class="aui-nav"><li><a href="/plugins/servlet/troubleshooting/view/"id="troubleshooting-home" title="Open Atlassian Troubleshooting and Support Tools"" >Troubleshooting and support tools</a></li><li><a href="/plugins/servlet/diagnostics/overview"id="diagnostics" title="Shows information about detected problems"" >Diagnostics</a></li><li><a href="/admin/logging" title="Configure logging and profiling."" >Logging and profiling</a></li></ul></div></nav></div><section class="aui-page-panel-content"><h2 class="page-panel-content-header">Jenkins Settings</h2><div id="jenkins-settings"><div id="project-key" style="display: none;"></div><div id="bitbucket-context" style="display: none;"></div></div></section></div></div></section><footer id="footer" role="contentinfo"><section class="notifications"></section><section class="footer-body"><ul><li data-key="footer.license.message">Git repository management for enterprise teams powered by <a href="http://www.atlassian.com/software/bitbucket/">Atlassian Bitbucket</a></li></ul><ul><li>Atlassian Bitbucket <span title="c4995b3e633957d958febdf1e3eece6d11715086" id="product-version" data-commitid="c4995b3e633957d958febdf1e3eece6d11715086" data-system-build-number="c4995b3"> v6.10.0</span></li><li data-key="footer.links.documentation"><a href="http://docs.atlassian.com/bitbucketserver/docs-0610/Bitbucket+Server+documentation?utm_campaign=in-app-help&amp;utm_medium=in-app-help&amp;utm_source=stash" target="_blank">Documentation</a></li><li data-key="footer.links.jac"><a href="https://jira.atlassian.com/browse/BSERV" target="_blank">Request a feature</a></li><li data-key="footer.links.about"><a href="/about">About</a></li><li data-key="footer.links.contact.atlassian"><a href="http://www.atlassian.com/company/contact/" target="_blank">Contact Atlassian</a></li></ul><div id="footer-logo"><a href="http://www.atlassian.com/" target="_blank">Atlassian</a></div></section></footer></div><script>require('bitbucket/internal/layout/base/base').onReady({id : 509, active: true, name : ""}, "Bitbucket" ); require('bitbucket/internal/widget/keyboard-shortcuts/keyboard-shortcuts').onReady();</script><script>require('bitbucket/internal/layout/admin/admin').onReady();</script><script type="text/javascript">require('bitbucket/internal/layout/base/menu/repositories/recent').initMenu('repositories-menu-trigger');</script><script type="text/javascript"> require('graphs/feature/recent-people').initMenu('#people-menu-trigger'); </script></body></html>


![image](https://user-images.githubusercontent.com/49514160/73739843-0da78d00-4758-11ea-9272-4d4e4860f421.png)

Request URL: https://stash.vsegda.da/rest/parameterized-builds/latest/global/servers

[{"csrf_enabled":false,"scope":"global","default_user":"jenkins_build","alias":null,"project":null,"root_token_enabled":false,"url":"my_url"}]

**Comment by a-hacker** [comment]
Fixed in version 4.0.12.
