### ISSUE TITLE
Add 'Needs Work' trigger

### ISSUE THREAD

**Issue by willehrlich** [ParameterizedBuilds/parameterized-builds#276]
Right now I have Jenkins jobs that are triggered based on a number of things that can take place in a pull request in Bitbucket.  I would like to handle the case where a code reviewer marks something as 'Needs Work' in a more graceful manner.  Currently in order to capture this, I have a Jenkins job running that periodically checks all open pull requests and does something if it finds a 'Needs Work' on any of them.  Not terribly efficient.

**Comment by a-hacker** [comment]
Hi @willehrlich. That seems like a reasonable feature to add. It is unlikely that I will get around to implementing this anytime soon. If you would be interested in working on this, I'd be happy to help however I can!

**Comment by a-hacker** [comment]
Closing this as enhancements are no longer being worked on.
