### ISSUE TITLE
Support Bitbucket Server v7.0

### ISSUE THREAD

**Issue by BoBiene** [ParameterizedBuilds/parameterized-builds#277]
The Plug-In is not working with the new Bitbucket v7.0

**Comment by a-hacker** [comment]
Hi @BoBiene. I have a branch ready to go for Bitbucket v7 [here](#265). I plan on doing a bit more testing before I release it though.

**Comment by a-hacker** [comment]
Version 5.0.0 released to add support for Bitbucket Server 7.X
