### ISSUE TITLE
PR manual trigger fails for projects that contain dots

### ISSUE THREAD

**Issue by alexrashed** [ParameterizedBuilds/parameterized-builds#289]
The bitbucket host is detected by evaluating regular expressions on several places in the source:
https://github.com/ParameterizedBuilds/parameterized-builds/blob/25148e596d3416a04d93ca8df9d7b309861d44c2/parameterized-client/src/hook/view.js#L11
https://github.com/ParameterizedBuilds/parameterized-builds/blob/aa7ac845a8859e7d28a504c2101ddddec4f06b6a/src/main/resources/scripts/jenkins/feature/build-dialog.js#L20
While the upper two regex allow any character in the name of the project (`.+?`), the regex in the PR view only allows `[\w_ -]+?`:
https://github.com/ParameterizedBuilds/parameterized-builds/blob/7593fef8ec2ae5ff40e93e036cd645b8c992becb/src/main/resources/scripts/jenkins/pb-pr-trigger.js#L17

This leads to an error when the project name does contain any other characters than [A-Z], [a-z], an underscore, a space or a dash (f.e. a dot).

A PR is in the making :)

PS.: Thanks for your work, it's a very useful plugin!

**Comment by a-hacker** [comment]
Thanks for the opening and fixing this issue @alexrashed. I'll get it released later today.
