### ISSUE TITLE
UI bug with checkboxes in Bitbucket 7.7+

### ISSUE THREAD

**Issue by PhilGrayson** [ParameterizedBuilds/parameterized-builds#367]
## Version Info

- _Parameterized Builds for Jenkins_:  5.0.2
- _Bitbucket Server_: 7.7 onwards
- _Jenkins_: N/A

## Expected Behavior
I expect to be able to select all checkbox parameters

## Current Behavior
I can select either one or no checkboxes.

[Here is a 35-second demonstration video of the bug](https://streamable.com/gi1ytw).

This is caused by an AUI update between 8.1.3 (used from Bitbucket 6.8 to 7.6) and 8.7.1 (used from Bitbucket 7.7) ([aui version matrix](https://bitbucket.org/atlassian/platform-module-usage/wiki/aui.md)).

[In the AUI upgrade guide, it lists changes to forms](https://aui.atlassian.com/aui/latest/docs/upgrades/aui-8.html#8.x-to-8.2).

There is a quick fix for this as demonstrated in the video. Add the `aui-legacy-forms` class to the `<form>` element will effectively undo the AUI changes.

However, clicking the label of one checkbox can alter the state of another checkbox. I demonstrated that in the demonstration video (at 28 second mark). This bug has existed in this plugin since before Bitbucket v7.7

**Comment by PhilGrayson** [comment]
>However, clicking the label of one checkbox can alter the state of another checkbox. I demonstrated that in the demonstration video (at 28 second mark). This bug has existed in this plugin since before Bitbucket v7.7

Ah, that's caused by issue #306.

**Comment by PhilGrayson** [comment]
In fact, the fix for #306 also fixes this issue.

Would you kindly publish a new version of this plugin?

**Comment by PhilGrayson** [comment]
In case anyone is wondering: I built and deployed a version to our production Bitbucket instance without issue.

I bumped the version in `pom.xml`, ran `mvn clean package` and then uploaded the resulting .jar file to Bitbucket (found in the `target/` directory).

I'd also like to say **thank you** to @KyleLNicholls and other contributors for this really handy plugin 🎉

**Comment by a-hacker** [comment]
Thanks for the investigations here @PhilGrayson and I really appreciate the video you linked! I've been absent for awhile but looking to push a 5.0.3 build later this week. That will likely be the last version of the plugin given that Bitbucket Server is about to hit the EOL for feature development and will fully EOL in a few years.
