### ISSUE TITLE
v5.2.0 - Unable to render configuration form for Parameterized Builds for Jenkins

### ISSUE THREAD

**Issue by carminevassallo** [ParameterizedBuilds/parameterized-builds#410]
Dear maintainers,

I'm experiencing the same render configuration form issue that @krm1 and the others were facing a few versions ago (see the corresponding [issue](https://github.com/ParameterizedBuilds/parameterized-builds/issues/183)). I commented on the previous issue but I haven't received any further replies. So I try to post it as a new issue.

## Version Info
Parameterized Builds for Jenkins_ plugin version: 5.2.0
Bitbucket_ version: 7.4.0
Jenkins_ Version: not relevant

## Detailed description of the issue
The plugin "Parameterized Builds for Jenkins" can't be configured on private repos (repos on your user rather than on a project - doesn't mean that the repo can't be visible to other users), it just shows "Unable to render configuration form for Parameterized Builds for Jenkins".

## Current Behavior
How to reproduce the issue:
- log in to bitbucket
- go to your own profile
- click on "create repository"
- give it some name and create it
- go to the settings of that repo
- go to "hooks"
- try to enable "Parameterized Builds for Jenkins"

As a result the following error is shown. 
![image](https://user-images.githubusercontent.com/23573650/119648147-66a1a580-be21-11eb-8853-70305913a1f0.png)

## Expected Behavior
After performing the previous steps, the config dialog for that plugin/hook opens.

**Comment by a-hacker** [comment]
@carminevassallo thanks for submitting this bug but the plugin doesn't support configurations for private repos. If anything the bug is that the hook shows up there in the first place. However, as far as I know there is no way to hide a hook so this is expected behavior.
