### ISSUE TITLE
How to reference Build Parameters in Jenkins?

### ISSUE THREAD

**Issue by Reyno851** [ParameterizedBuilds/parameterized-builds#427]
Hi, I am trying to pass in custom variables from BitBucket using Build parameters, but unable to receive it in jenkins. In jenkins, I have selected "This project is parameterized" and passed in the variable I have named in the "Name" section. However, when the job runs, the parameter is not received. How do I reference it? Is there some syntax I should be using at the jenkins side? Thanks

Key-value pair in Build Parameters:
TEST_VAR = $BRANCH

**Comment by a-hacker** [comment]
@Reyno851 you do not need spaces in between the = sign. On the jenkins side the job needs to be parameterized and have a parameter named exactly `TEST_VAR`. Any parameters passed to the build that aren't defined on the job are silently ignored by jenkins.
