### ISSUE TITLE
Plug-in not triggering Jenkins build when push performed but does trigger build manually from Bitbucket

### ISSUE THREAD

**Issue by AdrianMacFhearraigh** [ParameterizedBuilds/parameterized-builds#428]
We're currently using plug-in version 4.0.2 in a Bitbucket instance at V6.1.2. The plug-in is functioning fine for the vast majority of repos within this Bitbucket instance but we have a single project containing a few repos where it fails to trigger a Jenkins pipeline when a push is performed to the repos. As part of the review and investigation into this issue it was confirmed the manual build from Bitbucket successfully triggers the pipeline within Jenkins. Numerous other changes were performed as part of this investigation but none resolved the issue. We're currently testing the same plug-in configuration from a new project and repo to determine if it's corruption in the existing repo/plug-in inter-connectivity that fails to detect the push to trigger the Jenkins build. The new project and repo will hopefully prove this.

Attached is a Word doc containing screen shots of the plug-in configuration which I would be grateful if you could review in case there are errors in the configuration.

Is it possible for some internal Bitbucket - Plug-in interconnectivity corruption to occur that would be causing this issue?
How would I investigate if there was?
Would it be possible to fix this corruption if it existed or would we be advised to relocate to a new project and repo?
[Screen shots of Parameterized Build for Jenkins plug-in configuration for MIS_SM.docx](https://github.com/ParameterizedBuilds/parameterized-builds/files/7340112/Screen.shots.of.Parameterized.Build.for.Jenkins.plug-in.configuration.for.MIS_SM.docx)

**Comment by a-hacker** [comment]
@AdrianMacFhearraigh The 4.X builds of this plugin have not been supported for awhile. Unless this is an issue on the latest version, you'll have to fork the repo and create a custom build with a fix. You may want to look through more recent commits to see if an already existing change may solve your issue.
