### ISSUE TITLE
Bitbucket Repository containing dot (".") in a repository name doesnt trigger PR "Builds in Jenkins"

### ISSUE THREAD

**Issue by ckanakadas** [ParameterizedBuilds/parameterized-builds#429]
Bitbucket allow users to open repository with a name that contained a dot (".").
However, when using the hook of "Parameterized Builds for Jenkins" *from a pull request page*, there is an error if there is a dot in the repository's name.

We need:
1. Fix that problem within the hook.
2. Until that problem is fixed, we need to disable the possibility to name a repository with dot.

Could you please advise how exactly can i override the regular expression to point " var urlRegex = /(.+?)\/projects\/.+?\/repos\/.+?\/.*/"

Any alternatives to solve this problem ?

**Comment by a-hacker** [comment]
@ckanakadas I'm unable to replicate this. Repos with periods work just fine for me. That regex shouldn't be casuing issues either because the periods are just wildcards.
