### ISSUE TITLE
'Multibranch Pipeline' checkbox inoperative

### ISSUE THREAD

**Issue by terminalstderr** [ParameterizedBuilds/parameterized-builds#430]
## Version Info

- _Parameterized Builds for Jenkins_: 5.0.2
- _Bitbucket Server_: 7.17.1
- _Jenkins_: Not applicable (2.320)

## Expected Behavior

Clicking on the 'Multibranch Pipeline' checkbox works.

## Current Behavior

Clicking on the 'Multibranch Pipeline' checkbox does nothing.

> For existing Hooks that did have 'Multibranch Pipeline' checkbox selected, the setting persisted 👍. However, clicking on the checkbox does nothing 👎.

**Comment by terminalstderr** [comment]
A workaround:

1. First, create and save your Hook *without worrying about Multibranch Pipeline setting*
2. Re-open the Hook settings page
3. Open 'developer tools' in your browser 
    * E.g., right click on the relevant checkbox and click 'Inspect' (using Chrome)
4. Locate the relevant `input` field
    * E.g. `<input id="isPipeline-0" class="checkbox" name="isPipeline-1" type="checkbox" resolved>`
5. Add the attribute `checked="true"`
    * E.g. `<input id="isPipeline-0" class="checkbox" name="isPipeline-1" type="checkbox" resolved="" checked="True">`
6. Save!

This has worked for me!

**Comment by a-hacker** [comment]
Hi @terminalstderr, I believe this is an issue related to checkboxes that was introduced in Bitbucket 7.7+. There's already a fix on master but no release yet. I'm working on publishing a new build this week.

**Comment by cstmgl** [comment]
any update on this? for which version was this fixed sorry?
we have bitbucket server version 8.3 and still have this issue

**Comment by ryeleo** [comment]
Just so ppl know, this is still an issue on my current version of Bitbucket (Datacenter v8.9.11) -- I forget how to check the plugin version (I am not an Administrator of the Bitbucket instance)
