### ISSUE TITLE
Suggestion: Support for Multiple Jenkins Masters

### ISSUE THREAD

**Issue by chris-pardy** [ParameterizedBuilds/parameterized-builds#64]
We'd love to use this plugin but have multiple Jenkins Masters in order to let us scale out our build system better. It would be great if there was a way for us to load multiple Jenkins master instances into the settings of the plugin, and then choose the master node for each job we created.

**Comment by githubvmn** [comment]
Highly upvote this request!

**Comment by a-hacker** [comment]
Currently you can set different Jenkins servers at the project level. Is this sufficient?

**Comment by netropic** [comment]
@a-hacker ideally it would be at the repository level, but project-level may help. thanks for the reply!

**Comment by chris-pardy** [comment]
We have our Jenkins topology setup so each master manages a set of similar
executors (CI, Deployment, etc), so ideally we'd be able to setup a
different Jenkins master for each trigger.

**Comment by a-hacker** [comment]
@netropic, Setting up repo level settings shouldn't be too difficult. I'll see what I can do.

@chris-pardy, The idea of trigger-level Jenkins options is interesting but I have a hard time envisioning the UI for such a feature. If you could provide a mock-up of what that might look like, I'd be happy to look into it. An alternative though would be to have job-level Jenkins servers and a different Bitbucket job definition for each trigger (and thus a different Jenkins server for each trigger). It's a bit hacky but I think it might look cleaner in general.

**Comment by khuongdp** [comment]
+1 for repository level

**Comment by pduggishetti** [comment]
+1 for repository level

**Comment by AndreyB22** [comment]
Hi, we actually need multiple jenkins for the single repo, so it would be nice to have multiple jenkins setup and then choice list when configuring the hooks.
For example: 
hook1 with jenkinsA
hook2 with jenkinsB

**Comment by a-hacker** [comment]
Closing this as enhancements are no longer being worked on.
